package:
  name: ezrequest
  version: '2020.200.10'

source:
  git_url: https://github.com/coderepocenter/ezrequest
  git_rev: 2020.200.10

build:
  noarch: python
  number: 0

requirements:
  build:
    - git
  run:
    - python >= 3.6.10
    - requests >= 2.24.0
    - numpy >= 1.19.0
about:
  summary: A wrapper around requests making certain conditions easier.